### PR TITLE
Sheet/New/ageofficial

### PR DESCRIPTION
**Pull request by donbwhite**
## Submission Checklist
- [x] The Pull Request title contains the **short name** of the sheet being submitted.
- [x] The Pull Request title states the **type of change** being submitted (New/Update/Bugfix/etc.).
- [x] I have authorization from the game's publisher to make this an official sheet on Roll20 with their name attached.
- [x] This game is not a traditionally published game, but a copy of the game rules can be purchased/downloaded/found at: <   >
- [x] This sheet is for an unofficial fan game, modification to an existing game, or a homebrew system.

## New Sheet Checklist
If you are submitting a new sheet to the repository, please fill in any empty spaces indicated by `< >`.

- The full name of the game associated with the sheet is: `<AGE System>`  
  - _(i.e. Dungeons & Dragons 5th Edition, The Dresden Files RPG)_
- The name of this game system/family associated with the sheet is: `<Fantasy AGE, Modern AGE, Blue Rose>` 
  - _(i.e. Dungeons & Dragons, FATE)_
- The publisher of the game associated with the sheet is: `<Green Ronin Publishing>` 
  - _(i.e. Wizards of the Coast, Evil Hat)_

The information that is provided here will be used to help users find the sheet in Roll20 Tabletop and Roll20 Characters. Please make sure that all names that you provide read exactly how you'd like them to be displayed. To see example of where this information will show up, create a new game on Roll20. The Name and the publisher will show up in the dropdown menu and as the title of the sheet that is selected.

Please check any that apply:

# Changes / Description (optional)

Provide any notes relevant to this pull request here. This can include a description of the code changes, references to related pull requests, etc.

## More Help

Additional information for the beacon sdk can be found at the
[Beacon SDK Documentation Site](https://roll20.github.io/beacon-docs/docs/gettingstarted/introduction/).
You can also post additional questions using the
[Beacon Community GitHub Issues Tab](https://github.com/Roll20/roll20-beacon-sheets/issues).

### CODE REVIEW

**Comment by Alicekb** [comment]
Hey @donbwhite, apologizes for the delay.

There appears to already be a sheet named Age System in Roll20. Due shortnames having to be unique we can not use `age_system` or `agesystem`. The longname of Age System is also taken.

- The shortname is mostly an internally used value but it can  show up to users (such as in the url in Roll20 Characters).
- The long name is the name that appears in all the sheet selection drop downs.

Could you let me know an alternative name for the sheet's shortname and long name that would work, and if you could also update your PR so that the folder name matches that new shortname.

**Comment by donbwhite** [comment]
Hey @Alicekb ,

Sure, no problem. Is there a list of existing used Short & Long names so that I can make sure that we don't end up going back and forth on checking names? 

Also, will I need to make an update to rename the sheet's folder once the updated names have been decided upon?

**Comment by Alicekb** [comment]
We don't have a public list of shortnames, although a shortname of `"ageofficial"` would work along with the long name of `"AGE System Official"`.

yes if you can make an update to the folder name to "ageofficial" that would be great. We are going to enforce this going forward for Discord Activity compatibility.

**Comment by donbwhite** [comment]
Hey @Alicekb 

That works for me. I just updated the folder name in my commits. Both the short name and long name (ageofficial/AGE System Official) work for me.

**Comment by donbwhite** [comment]
@Alicekb Please let me know if any additional changes are needed. Thanks!

**Pull request merged**
